name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: sudo apt install -y nasm; sudo apt install -y binutils-x86-64-linux-gnu; sudo apt install -y build-essential; sudo apt install -y gcc-x86-64-linux-gnu
      
    - name: Setup directory
      run: make setup
  
    - name: Build
      run: make
