name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sh ./.github/workflows/configure.sh
    
    - name: Setup directory
      run: make setup

    - name: Build for x86-64
      run: make
